travel_respagence:
    pattern:  /
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:index" }

travel_respagence_show:
    pattern:  /{id}/show
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:show" }

travel_respagence_new:
    pattern:  /new
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:new" }

travel_respagence_create:
    pattern:  /create
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:create" }
    requirements: { _method: post }

travel_respagence_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:edit" }

travel_respagence_update:
    pattern:  /{id}/update
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:update" }
    requirements: { _method: post|put }

travel_respagence_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TravelAgenceBundle:RespoAgence:delete" }
    requirements: { _method: post|delete }
