travel_voypropose:
    pattern:  /
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:index" }

travel_voypropose_show:
    pattern:  /{id}/show
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:show" }

travel_voypropose_new:
    pattern:  /new
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:new" }

travel_voypropose_create:
    pattern:  /create
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:create" }
    requirements: { _method: post }

travel_voypropose_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:edit" }

travel_voypropose_update:
    pattern:  /{id}/update
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:update" }
    requirements: { _method: post|put }

travel_voypropose_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TravelAgenceBundle:VoyageurHasVoyage:delete" }
    requirements: { _method: post|delete }
