Travel\AgenceBundle\Entity\VoyageurHasVoyage:
    type: entity
    table: voyageur_has_voyage
    indexes:
        fk_voyageur_has_voyage_voyage1_idx:
            columns:
                - voyage_id
        fk_voyageur_has_voyage_voyageur1_idx:
            columns:
                - voyageur_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        voyageur:
            targetEntity: Voyageur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                voyageur_id:
                    referencedColumnName: id
            orphanRemoval: false
        voyage:
            targetEntity: Voyage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                voyage_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
