parameters:
#    travel_agence.example.class: Travel\AgenceBundle\Example

services:
#    travel_agence.example:
#        class: %travel_agence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
