Voyageur:
    type: entity
    table: voyageur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        eMail:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: e_mail
        password:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        dateInscription:
            type: date
            nullable: true
            comment: ''
            column: date_inscription
    lifecycleCallbacks: {  }
